<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\OfferwallsSetting;

class OfferwallsSettingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        OfferwallsSetting::insert([
            //for Adscendmedia
            ['name' => 'adscendmedia_api', 'value' => ''],
            ['name' => 'adscendmedia_pub_id', 'value' => ''],
            ['name' => 'adscendmedia_app_key', 'value' => ''],
            ['name' => 'adscendmedia_secret', 'value' => ''],
            ['name' => 'adscendmedia_hold', 'value' => '0'],
            ['name' => 'adscendmedia_hold_time', 'value' => '0'],
            ['name' => 'adscendmedia_min_hold_amount', 'value' => '0.5'],
            ['name' => 'adscendmedia_cp', 'value' => ''],
            ['name' => 'adscendmedia_starter_cp', 'value' => '30'],
            ['name' => 'adscendmedia_advanced_cp', 'value' => '50'],
            ['name' => 'adscendmedia_expert_cp', 'value' => '70'],
            ['name' => 'adscendmedia_ref_commission', 'value' => ''],
            ['name' => 'adscendmedia_status', 'value' => ''],
            ['name' => 'adscendmedia_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for adbreakmedia
            ['name' => 'adbreakmedia_api', 'value' => ''],
            ['name' => 'adbreakmedia_app_key', 'value' => ''],
            ['name' => 'adbreakmedia_secret', 'value' => ''],
            ['name' => 'adbreakmedia_hold', 'value' => '0'],
            ['name' => 'adbreakmedia_hold_time', 'value' => '0'],
            ['name' => 'adbreakmedia_min_hold_amount', 'value' => '0.5'],
            ['name' => 'adbreakmedia_cp', 'value' => ''],
            ['name' => 'adbreakmedia_starter_cp', 'value' => '30'],
            ['name' => 'adbreakmedia_advanced_cp', 'value' => '50'],
            ['name' => 'adbreakmedia_expert_cp', 'value' => '70'],
            ['name' => 'adbreakmedia_ref_commission', 'value' => ''],
            ['name' => 'adbreakmedia_status', 'value' => ''],
            ['name' => 'adbreakmedia_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for adgatemedia
            ['name' => 'adgatemedia_api', 'value' => ''],
            ['name' => 'adgatemedia_app_key', 'value' => ''],
            ['name' => 'adgatemedia_secret', 'value' => ''],
            ['name' => 'adgatemedia_hold', 'value' => '0'],
            ['name' => 'adgatemedia_hold_time', 'value' => '0'],
            ['name' => 'adgatemedia_min_hold_amount', 'value' => '0.5'],
            ['name' => 'adgatemedia_cp', 'value' => ''],
            ['name' => 'adgatemedia_starter_cp', 'value' => '30'],
            ['name' => 'adgatemedia_advanced_cp', 'value' => '50'],
            ['name' => 'adgatemedia_expert_cp', 'value' => '70'],
            ['name' => 'adgatemedia_ref_commission', 'value' => ''],
            ['name' => 'adgatemedia_status', 'value' => ''],
            ['name' => 'adgatemedia_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for adgem
            ['name' => 'adgem_api', 'value' => ''],
            ['name' => 'adgem_app_key', 'value' => ''],
            ['name' => 'adgem_secret', 'value' => ''],
            ['name' => 'adgem_hold', 'value' => '0'],
            ['name' => 'adgem_hold_time', 'value' => '0'],
            ['name' => 'adgem_min_hold_amount', 'value' => '0.5'],
            ['name' => 'adgem_cp', 'value' => ''],
            ['name' => 'adgem_starter_cp', 'value' => '30'],
            ['name' => 'adgem_advanced_cp', 'value' => '50'],
            ['name' => 'adgem_expert_cp', 'value' => '70'],
            ['name' => 'adgem_ref_commission', 'value' => ''],
            ['name' => 'adgem_status', 'value' => ''],
            ['name' => 'adgem_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for admandtium
            ['name' => 'admandtium_api', 'value' => ''],
            ['name' => 'admandtium_app_key', 'value' => ''],
            ['name' => 'admandtium_secret', 'value' => ''],
            ['name' => 'admandtium_hold', 'value' => '0'],
            ['name' => 'admandtium_hold_time', 'value' => '0'],
            ['name' => 'admandtium_min_hold_amount', 'value' => '0.5'],
            ['name' => 'admandtium_cp', 'value' => ''],
            ['name' => 'admandtium_starter_cp', 'value' => '30'],
            ['name' => 'admandtium_advanced_cp', 'value' => '50'],
            ['name' => 'admandtium_expert_cp', 'value' => '70'],
            ['name' => 'admandtium_ref_commission', 'value' => ''],
            ['name' => 'admandtium_status', 'value' => ''],
            ['name' => 'admandtium_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for adswedmedia
            ['name' => 'adswedmedia_api', 'value' => ''],
            ['name' => 'adswedmedia_app_key', 'value' => ''],
            ['name' => 'adswedmedia_secret', 'value' => ''],
            ['name' => 'adswedmedia_hold', 'value' => '0'],
            ['name' => 'adswedmedia_hold_time', 'value' => '0'],
            ['name' => 'adswedmedia_min_hold_amount', 'value' => '0.5'],
            ['name' => 'adswedmedia_cp', 'value' => ''],
            ['name' => 'adswedmedia_starter_cp', 'value' => '30'],
            ['name' => 'adswedmedia_advanced_cp', 'value' => '50'],
            ['name' => 'adswedmedia_expert_cp', 'value' => '70'],
            ['name' => 'adswedmedia_ref_commission', 'value' => ''],
            ['name' => 'adswedmedia_status', 'value' => ''],
            ['name' => 'adswedmedia_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for adworkmedia
            ['name' => 'adworkmedia_api', 'value' => ''],
            ['name' => 'adworkmedia_app_key', 'value' => ''],
            ['name' => 'adworkmedia_secret', 'value' => ''],
            ['name' => 'adworkmedia_hold', 'value' => '0'],
            ['name' => 'adworkmedia_hold_time', 'value' => '0'],
            ['name' => 'adworkmedia_min_hold_amount', 'value' => '0.5'],
            ['name' => 'adworkmedia_cp', 'value' => ''],
            ['name' => 'adworkmedia_starter_cp', 'value' => '30'],
            ['name' => 'adworkmedia_advanced_cp', 'value' => '50'],
            ['name' => 'adworkmedia_expert_cp', 'value' => '70'],
            ['name' => 'adworkmedia_ref_commission', 'value' => ''],
            ['name' => 'adworkmedia_status', 'value' => ''],
            ['name' => 'adworkmedia_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],
            //for ayetstudios
            ['name' => 'ayetstudios_api', 'value' => ''],
            ['name' => 'ayetstudios_pub_id', 'value' => ''],
            ['name' => 'ayetstudios_app_key', 'value' => ''],
            ['name' => 'ayetstudios_secret', 'value' => ''],
            ['name' => 'ayetstudios_hold', 'value' => '0'],
            ['name' => 'ayetstudios_hold_time', 'value' => '0'],
            ['name' => 'ayetstudios_min_hold_amount', 'value' => '0.5'],
            ['name' => 'ayetstudios_cp', 'value' => ''],
            ['name' => 'ayetstudios_starter_cp', 'value' => '30'],
            ['name' => 'ayetstudios_advanced_cp', 'value' => '50'],
            ['name' => 'ayetstudios_expert_cp', 'value' => '70'],
            ['name' => 'ayetstudios_ref_commission', 'value' => ''],
            ['name' => 'ayetstudios_status', 'value' => ''],
            ['name' => 'ayetstudios_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for bitcotasks
            ['name' => 'bitcotasks_api', 'value' => ''],
            ['name' => 'bitcotasks_app_key', 'value' => ''],
            ['name' => 'bitcotasks_secret', 'value' => ''],
            ['name' => 'bitcotasks_hold', 'value' => '0'],
            ['name' => 'bitcotasks_hold_time', 'value' => '0'],
            ['name' => 'bitcotasks_min_hold_amount', 'value' => '0.5'],
            ['name' => 'bitcotasks_cp', 'value' => ''],
            ['name' => 'bitcotasks_starter_cp', 'value' => '30'],
            ['name' => 'bitcotasks_advanced_cp', 'value' => '50'],
            ['name' => 'bitcotasks_expert_cp', 'value' => '70'],
            ['name' => 'bitcotasks_ref_commission', 'value' => ''],
            ['name' => 'bitcotasks_status', 'value' => ''],
            ['name' => 'bitcotasks_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for bitlabs
            ['name' => 'bitlabs_api', 'value' => ''],
            ['name' => 'bitlabs_app_key', 'value' => ''],
            ['name' => 'bitlabs_secret', 'value' => ''],
            ['name' => 'bitlabs_hold', 'value' => '0'],
            ['name' => 'bitlabs_hold_time', 'value' => '0'],
            ['name' => 'bitlabs_min_hold_amount', 'value' => '0.5'],
            ['name' => 'bitlabs_cp', 'value' => ''],
            ['name' => 'bitlabs_starter_cp', 'value' => '30'],
            ['name' => 'bitlabs_advanced_cp', 'value' => '50'],
            ['name' => 'bitlabs_expert_cp', 'value' => '70'],
            ['name' => 'bitlabs_ref_commission', 'value' => ''],
            ['name' => 'bitlabs_status', 'value' => ''],
            ['name' => 'bitlabs_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for cpxresearch
            ['name' => 'cpxresearch_api', 'value' => ''],
            ['name' => 'cpxresearch_app_key', 'value' => ''],
            ['name' => 'cpxresearch_secret', 'value' => ''],
            ['name' => 'cpxresearch_hold', 'value' => '0'],
            ['name' => 'cpxresearch_hold_time', 'value' => '0'],
            ['name' => 'cpxresearch_min_hold_amount', 'value' => '0.5'],
            ['name' => 'cpxresearch_cp', 'value' => ''],
            ['name' => 'cpxresearch_starter_cp', 'value' => '30'],
            ['name' => 'cpxresearch_advanced_cp', 'value' => '50'],
            ['name' => 'cpxresearch_expert_cp', 'value' => '70'],
            ['name' => 'cpxresearch_ref_commission', 'value' => ''],
            ['name' => 'cpxresearch_status', 'value' => ''],
            ['name' => 'cpxresearch_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for cpalead
            ['name' => 'cpalead_api', 'value' => ''],
            ['name' => 'cpalead_app_key', 'value' => ''],
            ['name' => 'cpalead_secret', 'value' => ''],
            ['name' => 'cpalead_hold', 'value' => '0'],
            ['name' => 'cpalead_hold_time', 'value' => '0'],
            ['name' => 'cpalead_min_hold_amount', 'value' => '0.5'],
            ['name' => 'cpalead_cp', 'value' => ''],
            ['name' => 'cpalead_starter_cp', 'value' => '30'],
            ['name' => 'cpalead_advanced_cp', 'value' => '50'],
            ['name' => 'cpalead_expert_cp', 'value' => '70'],
            ['name' => 'cpalead_ref_commission', 'value' => ''],
            ['name' => 'cpalead_status', 'value' => ''],
            ['name' => 'cpalead_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for excentiv
            ['name' => 'excentiv_api', 'value' => ''],
            ['name' => 'excentiv_app_key', 'value' => ''],
            ['name' => 'excentiv_secret', 'value' => ''],
            ['name' => 'excentiv_hold', 'value' => '0'],
            ['name' => 'excentiv_hold_time', 'value' => '0'],
            ['name' => 'excentiv_min_hold_amount', 'value' => '0.5'],
            ['name' => 'excentiv_cp', 'value' => ''],
            ['name' => 'excentiv_starter_cp', 'value' => '30'],
            ['name' => 'excentiv_advanced_cp', 'value' => '50'],
            ['name' => 'excentiv_expert_cp', 'value' => '70'],
            ['name' => 'excentiv_ref_commission', 'value' => ''],
            ['name' => 'excentiv_status', 'value' => ''],
            ['name' => 'excentiv_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for farly
            ['name' => 'farly_api', 'value' => ''],
            ['name' => 'farly_app_key', 'value' => ''],
            ['name' => 'farly_secret', 'value' => ''],
            ['name' => 'farly_hold', 'value' => '0'],
            ['name' => 'farly_hold_time', 'value' => '0'],
            ['name' => 'farly_min_hold_amount', 'value' => '0.5'],
            ['name' => 'farly_cp', 'value' => ''],
            ['name' => 'farly_starter_cp', 'value' => '30'],
            ['name' => 'farly_advanced_cp', 'value' => '50'],
            ['name' => 'farly_expert_cp', 'value' => '70'],
            ['name' => 'farly_ref_commission', 'value' => ''],
            ['name' => 'farly_status', 'value' => ''],
            ['name' => 'farly_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for hangmyads
            ['name' => 'hangmyads_api', 'value' => ''],
            ['name' => 'hangmyads_app_key', 'value' => ''],
            ['name' => 'hangmyads_secret', 'value' => ''],
            ['name' => 'hangmyads_hold', 'value' => '0'],
            ['name' => 'hangmyads_hold_time', 'value' => '0'],
            ['name' => 'hangmyads_min_hold_amount', 'value' => '0.5'],
            ['name' => 'hangmyads_cp', 'value' => ''],
            ['name' => 'hangmyads_starter_cp', 'value' => '30'],
            ['name' => 'hangmyads_advanced_cp', 'value' => '50'],
            ['name' => 'hangmyads_expert_cp', 'value' => '70'],
            ['name' => 'hangmyads_ref_commission', 'value' => ''],
            ['name' => 'hangmyads_status', 'value' => ''],
            ['name' => 'hangmyads_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],
            
            //for inbrain
            ['name' => 'inbrain_api', 'value' => ''],
            ['name' => 'inbrain_app_key', 'value' => ''],
            ['name' => 'inbrain_secret', 'value' => ''],
            ['name' => 'inbrain_hold', 'value' => '0'],
            ['name' => 'inbrain_hold_time', 'value' => '0'],
            ['name' => 'inbrain_min_hold_amount', 'value' => '0.5'],
            ['name' => 'inbrain_cp', 'value' => ''],
            ['name' => 'inbrain_starter_cp', 'value' => '30'],
            ['name' => 'inbrain_advanced_cp', 'value' => '50'],
            ['name' => 'inbrain_expert_cp', 'value' => '70'],
            ['name' => 'inbrain_ref_commission', 'value' => ''],
            ['name' => 'inbrain_status', 'value' => ''],
            ['name' => 'inbrain_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for kiwiwall
            ['name' => 'kiwiwall_api', 'value' => ''],
            ['name' => 'kiwiwall_app_key', 'value' => ''],
            ['name' => 'kiwiwall_secret', 'value' => ''],
            ['name' => 'kiwiwall_hold', 'value' => '0'],
            ['name' => 'kiwiwall_hold_time', 'value' => '0'],
            ['name' => 'kiwiwall_min_hold_amount', 'value' => '0.5'],
            ['name' => 'kiwiwall_cp', 'value' => ''],
            ['name' => 'kiwiwall_starter_cp', 'value' => '30'],
            ['name' => 'kiwiwall_advanced_cp', 'value' => '50'],
            ['name' => 'kiwiwall_expert_cp', 'value' => '70'],
            ['name' => 'kiwiwall_ref_commission', 'value' => ''],
            ['name' => 'kiwiwall_status', 'value' => ''],
            ['name' => 'kiwiwall_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for lootably
            ['name' => 'lootably_api', 'value' => ''],
            ['name' => 'lootably_app_key', 'value' => ''],
            ['name' => 'lootably_secret', 'value' => ''],
            ['name' => 'lootably_hold', 'value' => '0'],
            ['name' => 'lootably_hold_time', 'value' => '0'],
            ['name' => 'lootably_min_hold_amount', 'value' => '0.5'],
            ['name' => 'lootably_cp', 'value' => ''],
            ['name' => 'lootably_starter_cp', 'value' => '30'],
            ['name' => 'lootably_advanced_cp', 'value' => '50'],
            ['name' => 'lootably_expert_cp', 'value' => '70'],
            ['name' => 'lootably_ref_commission', 'value' => ''],
            ['name' => 'lootably_status', 'value' => ''],
            ['name' => 'lootably_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for monlix
            ['name' => 'monlix_api', 'value' => ''],
            ['name' => 'monlix_app_key', 'value' => ''],
            ['name' => 'monlix_secret', 'value' => ''],
            ['name' => 'monlix_hold', 'value' => '0'],
            ['name' => 'monlix_hold_time', 'value' => '0'],
            ['name' => 'monlix_min_hold_amount', 'value' => '0.5'],
            ['name' => 'monlix_cp', 'value' => ''],
            ['name' => 'monlix_starter_cp', 'value' => '30'],
            ['name' => 'monlix_advanced_cp', 'value' => '50'],
            ['name' => 'monlix_expert_cp', 'value' => '70'],
            ['name' => 'monlix_ref_commission', 'value' => ''],
            ['name' => 'monlix_status', 'value' => ''],
            ['name' => 'monlix_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],
            
            //for mychips
            ['name' => 'mychips_api', 'value' => ''],
            ['name' => 'mychips_app_key', 'value' => ''],
            ['name' => 'mychips_secret', 'value' => ''],
            ['name' => 'mychips_hold', 'value' => '0'],
            ['name' => 'mychips_hold_time', 'value' => '0'],
            ['name' => 'mychips_min_hold_amount', 'value' => '0.5'],
            ['name' => 'mychips_cp', 'value' => ''],
            ['name' => 'mychips_starter_cp', 'value' => '30'],
            ['name' => 'mychips_advanced_cp', 'value' => '50'],
            ['name' => 'mychips_expert_cp', 'value' => '70'],
            ['name' => 'mychips_ref_commission', 'value' => ''],
            ['name' => 'mychips_status', 'value' => ''],
            ['name' => 'mychips_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for notik
            ['name' => 'notik_api', 'value' => ''],
            ['name' => 'notik_pub_key', 'value' => ''],
            ['name' => 'notik_app_key', 'value' => ''],
            ['name' => 'notik_secret', 'value' => ''],
            ['name' => 'notik_hold', 'value' => '0'],
            ['name' => 'notik_hold_time', 'value' => '0'],
            ['name' => 'notik_min_hold_amount', 'value' => '0.5'],
            ['name' => 'notik_cp', 'value' => ''],
            ['name' => 'notik_starter_cp', 'value' => '30'],
            ['name' => 'notik_advanced_cp', 'value' => '50'],
            ['name' => 'notik_expert_cp', 'value' => '70'],
            ['name' => 'notik_ref_commission', 'value' => ''],
            ['name' => 'notik_status', 'value' => ''],
            ['name' => 'notik_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],
            
            //for offers4crypto
            ['name' => 'offers4crypto_api', 'value' => ''],
            ['name' => 'offers4crypto_app_key', 'value' => ''],
            ['name' => 'offers4crypto_secret', 'value' => ''],
            ['name' => 'offers4crypto_hold', 'value' => '0'],
            ['name' => 'offers4crypto_hold_time', 'value' => '0'],
            ['name' => 'offers4crypto_min_hold_amount', 'value' => '0.5'],
            ['name' => 'offers4crypto_cp', 'value' => ''],
            ['name' => 'offers4crypto_starter_cp', 'value' => '30'],
            ['name' => 'offers4crypto_advanced_cp', 'value' => '50'],
            ['name' => 'offers4crypto_expert_cp', 'value' => '70'],
            ['name' => 'offers4crypto_ref_commission', 'value' => ''],
            ['name' => 'offers4crypto_status', 'value' => ''],
            ['name' => 'offers4crypto_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],
            
            //for offertoro
            ['name' => 'offertoro_api', 'value' => ''],
            ['name' => 'offertoro_app_key', 'value' => ''],
            ['name' => 'offertoro_secret', 'value' => ''],
            ['name' => 'offertoro_hold', 'value' => '0'],
            ['name' => 'offertoro_hold_time', 'value' => '0'],
            ['name' => 'offertoro_min_hold_amount', 'value' => '0.5'],
            ['name' => 'offertoro_cp', 'value' => ''],
            ['name' => 'offertoro_starter_cp', 'value' => '30'],
            ['name' => 'offertoro_advanced_cp', 'value' => '50'],
            ['name' => 'offertoro_expert_cp', 'value' => '70'],
            ['name' => 'offertoro_ref_commission', 'value' => ''],
            ['name' => 'offertoro_status', 'value' => ''],
            ['name' => 'offertoro_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for ogads
            ['name' => 'ogads_api', 'value' => ''],
            ['name' => 'ogads_app_key', 'value' => ''],
            ['name' => 'ogads_secret', 'value' => ''],
            ['name' => 'ogads_hold', 'value' => '0'],
            ['name' => 'ogads_hold_time', 'value' => '0'],
            ['name' => 'ogads_min_hold_amount', 'value' => '0.5'],
            ['name' => 'ogads_cp', 'value' => ''],
            ['name' => 'ogads_starter_cp', 'value' => '30'],
            ['name' => 'ogads_advanced_cp', 'value' => '50'],
            ['name' => 'ogads_expert_cp', 'value' => '70'],
            ['name' => 'ogads_ref_commission', 'value' => ''],
            ['name' => 'ogads_status', 'value' => ''],
            ['name' => 'ogads_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for pointclick
            ['name' => 'pointclick_api', 'value' => ''],
            ['name' => 'pointclick_app_key', 'value' => ''],
            ['name' => 'pointclick_secret', 'value' => ''],
            ['name' => 'pointclick_hold', 'value' => '0'],
            ['name' => 'pointclick_hold_time', 'value' => '0'],
            ['name' => 'pointclick_min_hold_amount', 'value' => '0.5'],
            ['name' => 'pointclick_cp', 'value' => ''],
            ['name' => 'pointclick_starter_cp', 'value' => '30'],
            ['name' => 'pointclick_advanced_cp', 'value' => '50'],
            ['name' => 'pointclick_expert_cp', 'value' => '70'],
            ['name' => 'pointclick_ref_commission', 'value' => ''],
            ['name' => 'pointclick_status', 'value' => ''],
            ['name' => 'pointclick_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for pollfish
            ['name' => 'pollfish_api', 'value' => ''],
            ['name' => 'pollfish_app_key', 'value' => ''],
            ['name' => 'pollfish_secret', 'value' => ''],
            ['name' => 'pollfish_hold', 'value' => '0'],
            ['name' => 'pollfish_hold_time', 'value' => '0'],
            ['name' => 'pollfish_min_hold_amount', 'value' => '0.5'],
            ['name' => 'pollfish_cp', 'value' => ''],
            ['name' => 'pollfish_starter_cp', 'value' => '30'],
            ['name' => 'pollfish_advanced_cp', 'value' => '50'],
            ['name' => 'pollfish_expert_cp', 'value' => '70'],
            ['name' => 'pollfish_ref_commission', 'value' => ''],
            ['name' => 'pollfish_status', 'value' => ''],
            ['name' => 'pollfish_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for revlum
            ['name' => 'revlum_api', 'value' => ''],
            ['name' => 'revlum_app_key', 'value' => ''],
            ['name' => 'revlum_secret', 'value' => ''],
            ['name' => 'revlum_hold', 'value' => '0'],
            ['name' => 'revlum_hold_time', 'value' => '0'],
            ['name' => 'revlum_min_hold_amount', 'value' => '0.5'],
            ['name' => 'revlum_cp', 'value' => ''],
            ['name' => 'revlum_starter_cp', 'value' => '30'],
            ['name' => 'revlum_advanced_cp', 'value' => '50'],
            ['name' => 'revlum_expert_cp', 'value' => '70'],
            ['name' => 'revlum_ref_commission', 'value' => ''],
            ['name' => 'revlum_status', 'value' => ''],
            ['name' => 'revlum_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],
            
            //for sasysorewards
            ['name' => 'sasysorewards_api', 'value' => ''],
            ['name' => 'sasysorewards_app_key', 'value' => ''],
            ['name' => 'sasysorewards_secret', 'value' => ''],
            ['name' => 'sasysorewards_hold', 'value' => '0'],
            ['name' => 'sasysorewards_hold_time', 'value' => '0'],
            ['name' => 'sasysorewards_min_hold_amount', 'value' => '0.5'],
            ['name' => 'sasysorewards_cp', 'value' => ''],
            ['name' => 'sasysorewards_starter_cp', 'value' => '30'],
            ['name' => 'sasysorewards_advanced_cp', 'value' => '50'],
            ['name' => 'sasysorewards_expert_cp', 'value' => '70'],
            ['name' => 'sasysorewards_ref_commission', 'value' => ''],
            ['name' => 'sasysorewards_status', 'value' => ''],
            ['name' => 'sasysorewards_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for sushiads
            ['name' => 'sushiads_api', 'value' => ''],
            ['name' => 'sushiads_app_key', 'value' => ''],
            ['name' => 'sushiads_secret', 'value' => ''],
            ['name' => 'sushiads_hold', 'value' => '0'],
            ['name' => 'sushiads_hold_time', 'value' => '0'],
            ['name' => 'sushiads_min_hold_amount', 'value' => '0.5'],
            ['name' => 'sushiads_cp', 'value' => ''],
            ['name' => 'sushiads_starter_cp', 'value' => '30'],
            ['name' => 'sushiads_advanced_cp', 'value' => '50'],
            ['name' => 'sushiads_expert_cp', 'value' => '70'],
            ['name' => 'sushiads_ref_commission', 'value' => ''],
            ['name' => 'sushiads_status', 'value' => ''],
            ['name' => 'sushiads_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for tapresearch
            ['name' => 'tapresearch_api', 'value' => ''],
            ['name' => 'tapresearch_app_key', 'value' => ''],
            ['name' => 'tapresearch_secret', 'value' => ''],
            ['name' => 'tapresearch_hold', 'value' => '0'],
            ['name' => 'tapresearch_hold_time', 'value' => '0'],
            ['name' => 'tapresearch_min_hold_amount', 'value' => '0.5'],
            ['name' => 'tapresearch_cp', 'value' => ''],
            ['name' => 'tapresearch_starter_cp', 'value' => '30'],
            ['name' => 'tapresearch_advanced_cp', 'value' => '50'],
            ['name' => 'tapresearch_expert_cp', 'value' => '70'],
            ['name' => 'tapresearch_ref_commission', 'value' => ''],
            ['name' => 'tapresearch_status', 'value' => ''],
            ['name' => 'tapresearch_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for timewall
            ['name' => 'timewall_api', 'value' => ''],
            ['name' => 'timewall_app_key', 'value' => ''],
            ['name' => 'timewall_secret', 'value' => ''],
            ['name' => 'timewall_hold', 'value' => '0'],
            ['name' => 'timewall_hold_time', 'value' => '0'],
            ['name' => 'timewall_min_hold_amount', 'value' => '0.5'],
            ['name' => 'timewall_cp', 'value' => ''],
            ['name' => 'timewall_starter_cp', 'value' => '30'],
            ['name' => 'timewall_advanced_cp', 'value' => '50'],
            ['name' => 'timewall_expert_cp', 'value' => '70'],
            ['name' => 'timewall_ref_commission', 'value' => ''],
            ['name' => 'timewall_status', 'value' => ''],
            ['name' => 'timewall_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for theoremreach
            ['name' => 'theoremreach_api', 'value' => ''],
            ['name' => 'theoremreach_app_key', 'value' => ''],
            ['name' => 'theoremreach_secret', 'value' => ''],
            ['name' => 'theoremreach_hold', 'value' => '0'],
            ['name' => 'theoremreach_hold_time', 'value' => '0'],
            ['name' => 'theoremreach_min_hold_amount', 'value' => '0.5'],
            ['name' => 'theoremreach_cp', 'value' => ''],
            ['name' => 'theoremreach_starter_cp', 'value' => '30'],
            ['name' => 'theoremreach_advanced_cp', 'value' => '50'],
            ['name' => 'theoremreach_expert_cp', 'value' => '70'],
            ['name' => 'theoremreach_ref_commission', 'value' => ''],
            ['name' => 'theoremreach_status', 'value' => ''],
            ['name' => 'theoremreach_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for wannads
            ['name' => 'wannads_api', 'value' => ''],
            ['name' => 'wannads_app_key', 'value' => ''],
            ['name' => 'wannads_secret', 'value' => ''],
            ['name' => 'wannads_hold', 'value' => '0'],
            ['name' => 'wannads_hold_time', 'value' => '0'],
            ['name' => 'wannads_min_hold_amount', 'value' => '0.5'],
            ['name' => 'wannads_cp', 'value' => ''],
            ['name' => 'wannads_starter_cp', 'value' => '30'],
            ['name' => 'wannads_advanced_cp', 'value' => '50'],
            ['name' => 'wannads_expert_cp', 'value' => '70'],
            ['name' => 'wannads_ref_commission', 'value' => ''],
            ['name' => 'wannads_status', 'value' => ''],
            ['name' => 'wannads_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],

            //for yoursurveys
            ['name' => 'yoursurveys_api', 'value' => ''],
            ['name' => 'yoursurveys_app_key', 'value' => ''],
            ['name' => 'yoursurveys_secret', 'value' => ''],
            ['name' => 'yoursurveys_hold', 'value' => '0'],
            ['name' => 'yoursurveys_hold_time', 'value' => '0'],
            ['name' => 'yoursurveys_min_hold_amount', 'value' => '0.5'],
            ['name' => 'yoursurveys_cp', 'value' => ''],
            ['name' => 'yoursurveys_starter_cp', 'value' => '30'],
            ['name' => 'yoursurveys_advanced_cp', 'value' => '50'],
            ['name' => 'yoursurveys_expert_cp', 'value' => '70'],
            ['name' => 'yoursurveys_ref_commission', 'value' => ''],
            ['name' => 'yoursurveys_status', 'value' => ''],
            ['name' => 'yoursurveys_whitelisted_ips', 'value' => json_encode(['192.168.1.1', '192.168.1.2', '192.168.1.3'])],
        ]);
    }
}
